/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNewRouteImport } from './routes/_authenticated/app.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAppInstallmentsIndexRouteImport } from './routes/_authenticated/app.installments.index'
import { Route as AuthenticatedAdminInvestorsIndexRouteImport } from './routes/_authenticated/admin.investors.index'
import { Route as AuthenticatedAdminContractsIndexRouteImport } from './routes/_authenticated/admin.contracts.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedAdminApplicationsIndexRouteImport } from './routes/_authenticated/admin.applications.index'
import { Route as AuthenticatedAppInstallmentsIdRouteImport } from './routes/_authenticated/app.installments.$id'
import { Route as AuthenticatedAdminInvestorsNewRouteImport } from './routes/_authenticated/admin.investors.new'
import { Route as AuthenticatedAdminInvestorsIdRouteImport } from './routes/_authenticated/admin.investors.$id'
import { Route as AuthenticatedAdminInstallmentsNewRouteImport } from './routes/_authenticated/admin.installments.new'
import { Route as AuthenticatedAdminContractsIdRouteImport } from './routes/_authenticated/admin.contracts.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedAdminApplicationsIdRouteImport } from './routes/_authenticated/admin.applications.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewRoute = AuthenticatedAppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppInstallmentsIndexRoute =
  AuthenticatedAppInstallmentsIndexRouteImport.update({
    id: '/installments/',
    path: '/installments/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminInvestorsIndexRoute =
  AuthenticatedAdminInvestorsIndexRouteImport.update({
    id: '/investors/',
    path: '/investors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsIndexRoute =
  AuthenticatedAdminContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminApplicationsIndexRoute =
  AuthenticatedAdminApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppInstallmentsIdRoute =
  AuthenticatedAppInstallmentsIdRouteImport.update({
    id: '/installments/$id',
    path: '/installments/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminInvestorsNewRoute =
  AuthenticatedAdminInvestorsNewRouteImport.update({
    id: '/investors/new',
    path: '/investors/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvestorsIdRoute =
  AuthenticatedAdminInvestorsIdRouteImport.update({
    id: '/investors/$id',
    path: '/investors/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstallmentsNewRoute =
  AuthenticatedAdminInstallmentsNewRouteImport.update({
    id: '/installments/new',
    path: '/installments/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsIdRoute =
  AuthenticatedAdminContractsIdRouteImport.update({
    id: '/contracts/$id',
    path: '/contracts/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminApplicationsIdRoute =
  AuthenticatedAdminApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/contracts/$id': typeof AuthenticatedAdminContractsIdRoute
  '/admin/installments/new': typeof AuthenticatedAdminInstallmentsNewRoute
  '/admin/investors/$id': typeof AuthenticatedAdminInvestorsIdRoute
  '/admin/investors/new': typeof AuthenticatedAdminInvestorsNewRoute
  '/app/installments/$id': typeof AuthenticatedAppInstallmentsIdRoute
  '/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
  '/admin/investors/': typeof AuthenticatedAdminInvestorsIndexRoute
  '/app/installments/': typeof AuthenticatedAppInstallmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/contracts/$id': typeof AuthenticatedAdminContractsIdRoute
  '/admin/installments/new': typeof AuthenticatedAdminInstallmentsNewRoute
  '/admin/investors/$id': typeof AuthenticatedAdminInvestorsIdRoute
  '/admin/investors/new': typeof AuthenticatedAdminInvestorsNewRoute
  '/app/installments/$id': typeof AuthenticatedAppInstallmentsIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsIndexRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsIndexRoute
  '/app/installments': typeof AuthenticatedAppInstallmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/new': typeof AuthenticatedAppNewRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/contracts/$id': typeof AuthenticatedAdminContractsIdRoute
  '/_authenticated/admin/installments/new': typeof AuthenticatedAdminInstallmentsNewRoute
  '/_authenticated/admin/investors/$id': typeof AuthenticatedAdminInvestorsIdRoute
  '/_authenticated/admin/investors/new': typeof AuthenticatedAdminInvestorsNewRoute
  '/_authenticated/app/installments/$id': typeof AuthenticatedAppInstallmentsIdRoute
  '/_authenticated/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
  '/_authenticated/admin/investors/': typeof AuthenticatedAdminInvestorsIndexRoute
  '/_authenticated/app/installments/': typeof AuthenticatedAppInstallmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/payments'
    | '/admin/users'
    | '/app/new'
    | '/app/profile'
    | '/admin/'
    | '/app/'
    | '/admin/applications/$id'
    | '/admin/clients/$id'
    | '/admin/contracts/$id'
    | '/admin/installments/new'
    | '/admin/investors/$id'
    | '/admin/investors/new'
    | '/app/installments/$id'
    | '/admin/applications/'
    | '/admin/clients/'
    | '/admin/contracts/'
    | '/admin/investors/'
    | '/app/installments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/payments'
    | '/admin/users'
    | '/app/new'
    | '/app/profile'
    | '/admin'
    | '/app'
    | '/admin/applications/$id'
    | '/admin/clients/$id'
    | '/admin/contracts/$id'
    | '/admin/installments/new'
    | '/admin/investors/$id'
    | '/admin/investors/new'
    | '/app/installments/$id'
    | '/admin/applications'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/investors'
    | '/app/installments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/new'
    | '/_authenticated/app/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/applications/$id'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/contracts/$id'
    | '/_authenticated/admin/installments/new'
    | '/_authenticated/admin/investors/$id'
    | '/_authenticated/admin/investors/new'
    | '/_authenticated/app/installments/$id'
    | '/_authenticated/admin/applications/'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/contracts/'
    | '/_authenticated/admin/investors/'
    | '/_authenticated/app/installments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new': {
      id: '/_authenticated/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthenticatedAppNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/installments/': {
      id: '/_authenticated/app/installments/'
      path: '/installments'
      fullPath: '/app/installments/'
      preLoaderRoute: typeof AuthenticatedAppInstallmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/investors/': {
      id: '/_authenticated/admin/investors/'
      path: '/investors'
      fullPath: '/admin/investors/'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts/': {
      id: '/_authenticated/admin/contracts/'
      path: '/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AuthenticatedAdminContractsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/applications/': {
      id: '/_authenticated/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/installments/$id': {
      id: '/_authenticated/app/installments/$id'
      path: '/installments/$id'
      fullPath: '/app/installments/$id'
      preLoaderRoute: typeof AuthenticatedAppInstallmentsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/investors/new': {
      id: '/_authenticated/admin/investors/new'
      path: '/investors/new'
      fullPath: '/admin/investors/new'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/investors/$id': {
      id: '/_authenticated/admin/investors/$id'
      path: '/investors/$id'
      fullPath: '/admin/investors/$id'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/installments/new': {
      id: '/_authenticated/admin/installments/new'
      path: '/installments/new'
      fullPath: '/admin/installments/new'
      preLoaderRoute: typeof AuthenticatedAdminInstallmentsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts/$id': {
      id: '/_authenticated/admin/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/admin/contracts/$id'
      preLoaderRoute: typeof AuthenticatedAdminContractsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/applications/$id': {
      id: '/_authenticated/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApplicationsIdRoute: typeof AuthenticatedAdminApplicationsIdRoute
  AuthenticatedAdminContractsIdRoute: typeof AuthenticatedAdminContractsIdRoute
  AuthenticatedAdminInstallmentsNewRoute: typeof AuthenticatedAdminInstallmentsNewRoute
  AuthenticatedAdminInvestorsIdRoute: typeof AuthenticatedAdminInvestorsIdRoute
  AuthenticatedAdminInvestorsNewRoute: typeof AuthenticatedAdminInvestorsNewRoute
  AuthenticatedAdminApplicationsIndexRoute: typeof AuthenticatedAdminApplicationsIndexRoute
  AuthenticatedAdminContractsIndexRoute: typeof AuthenticatedAdminContractsIndexRoute
  AuthenticatedAdminInvestorsIndexRoute: typeof AuthenticatedAdminInvestorsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApplicationsIdRoute: AuthenticatedAdminApplicationsIdRoute,
  AuthenticatedAdminContractsIdRoute: AuthenticatedAdminContractsIdRoute,
  AuthenticatedAdminInstallmentsNewRoute:
    AuthenticatedAdminInstallmentsNewRoute,
  AuthenticatedAdminInvestorsIdRoute: AuthenticatedAdminInvestorsIdRoute,
  AuthenticatedAdminInvestorsNewRoute: AuthenticatedAdminInvestorsNewRoute,
  AuthenticatedAdminApplicationsIndexRoute:
    AuthenticatedAdminApplicationsIndexRoute,
  AuthenticatedAdminContractsIndexRoute: AuthenticatedAdminContractsIndexRoute,
  AuthenticatedAdminInvestorsIndexRoute: AuthenticatedAdminInvestorsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppNewRoute: typeof AuthenticatedAppNewRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppInstallmentsIdRoute: typeof AuthenticatedAppInstallmentsIdRoute
  AuthenticatedAppInstallmentsIndexRoute: typeof AuthenticatedAppInstallmentsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppNewRoute: AuthenticatedAppNewRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppInstallmentsIdRoute: AuthenticatedAppInstallmentsIdRoute,
  AuthenticatedAppInstallmentsIndexRoute:
    AuthenticatedAppInstallmentsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
